/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.CarroDAO;
import controle.CategoriasDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Carro;
import modelo.Categoria;

/**
 *
 * @author Renato
 */
public class TelaCarros extends javax.swing.JFrame {

    DefaultTableModel modeloTabela = new DefaultTableModel(new Object[][]{}, new Object[]{"ID", "Nome", "Placa", "Marca", "Chasi", "Ano", "Categoria", "Oculto"});

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy");

    /**
     * Creates new form TelaCarros
     */
    public TelaCarros() {
        initComponents();
        tblCarros.setModel(modeloTabela);
        tblCarros.removeColumn(tblCarros.getColumnModel().getColumn(7));

        carregarCarros();
        carregarCategorias();

    }

    public void carregarCarros() {
        modeloTabela.setNumRows(0);

        CarroDAO dao = new CarroDAO();
        for (Carro c : dao.buscarcarros()) {
            modeloTabela.addRow(new Object[]{c.getId(), c.getNome(), c.getPlaca(), c.getMarca(), c.getChasi(), sdf.format(c.getAno()), c.getCategoria().getNome_cat(), c});

        }

    }

    public void carregarCategorias() {
        cmbCategorias.removeAllItems();
        CategoriasDAO dao = new CategoriasDAO();
        cmbCategorias.addItem(null);
        for (Categoria u : dao.buscarcategorias()) {
            cmbCategorias.addItem(u);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCarros = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        txtCarros = new javax.swing.JTextField();
        cmbCategorias = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCarros);

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        txtCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarrosActionPerformed(evt);
            }
        });
        txtCarros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCarrosKeyReleased(evt);
            }
        });

        cmbCategorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCategoriasItemStateChanged(evt);
            }
        });
        cmbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriasActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria: ");

        jLabel2.setText("Nome do carro:");

        jLabel3.setText("Carros Cadastrados");

        jButton1.setText("Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(26, 26, 26)
                            .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtCarros, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEditar)
                    .addComponent(btnRemover)
                    .addComponent(jButton1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        CadastrarCarros tela = new CadastrarCarros(this, rootPaneCheckingEnabled);
        tela.setVisible(true);

        Carro novo = tela.getCarro();

        if (novo != null) {
            CarroDAO dao = new CarroDAO();
            dao.inserir(novo);
            carregarCarros();
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        try {
            int indiceLinha = tblCarros.getSelectedRow();

            Carro selecionado = (Carro) modeloTabela.getValueAt(indiceLinha, 7);
            if (selecionado != null) {
                int op = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o carro selecionada?");
                if (op == JOptionPane.YES_NO_OPTION) {

                    CarroDAO dao = new CarroDAO();
                    dao.remover(selecionado);

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Escolheu não excluir o carro");
                }
                carregarCarros();

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um carro para remover " + e.getMessage());
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed

        int indiceLinha = tblCarros.getSelectedRow();
        if (indiceLinha != -1) {

            Carro selecionado = (Carro) modeloTabela.getValueAt(indiceLinha, 7);

            CadastrarCarros tela = new CadastrarCarros(this, rootPaneCheckingEnabled);
            tela.setCarro(selecionado);
            tela.setVisible(true);

            if (selecionado != null) {
                CarroDAO dao = new CarroDAO();
                dao.editar(selecionado);
                carregarCarros();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Carro ");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarrosActionPerformed

    private void txtCarrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCarrosKeyReleased
        Categoria catSel = (Categoria) cmbCategorias.getSelectedItem();
        String nome = txtCarros.getText().trim().toLowerCase();
        if (catSel != null) {
            modeloTabela.setNumRows(0);
            CarroDAO dao = new CarroDAO();
//        ArrayList<Cidade> lista = dao.buscar();
            for (Carro c : dao.buscar(catSel, nome)) {

                modeloTabela.addRow(new Object[]{c.getId(), c.getNome(), c.getMarca(), c.getPlaca(), c.getChasi(), sdf.format(c.getAno()), c.getCategoria().getNome_cat()});
            }
        } else {
            modeloTabela.setNumRows(0);
            CarroDAO dao = new CarroDAO();
            for (Carro c : dao.buscar(nome)) {
                modeloTabela.addRow(new Object[]{c.getId(), c.getNome(), c.getMarca(), c.getPlaca(), c.getChasi(), sdf.format(c.getAno()), c.getCategoria().getNome_cat()});

            }
        }
    }//GEN-LAST:event_txtCarrosKeyReleased

    private void cmbCategoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCategoriasItemStateChanged
        Categoria catSel = (Categoria) cmbCategorias.getSelectedItem();
        String nome = txtCarros.getText().trim().toLowerCase();
        if (catSel != null) {
            modeloTabela.setNumRows(0);
            CarroDAO dao = new CarroDAO();
//        ArrayList<Cidade> lista = dao.buscar();
            for (Carro c : dao.buscar(catSel, nome)) {

                modeloTabela.addRow(new Object[]{c.getId(), c.getNome(), c.getMarca(), c.getPlaca(), c.getChasi(), c.getAno(), c.getCategoria().getNome_cat()});
            }
        } else {
            modeloTabela.setNumRows(0);
            CarroDAO dao = new CarroDAO();
            for (Carro c : dao.buscar(nome)) {
                modeloTabela.addRow(new Object[]{c.getId(), c.getNome(), c.getMarca(), c.getPlaca(), c.getChasi(), c.getAno(), c.getCategoria().getNome_cat()});

            }
        }
    }//GEN-LAST:event_cmbCategoriasItemStateChanged

    private void cmbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int sel = tblCarros.getSelectedRow();

        System.out.println("sel: " + sel);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<Categoria> cmbCategorias;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCarros;
    private javax.swing.JTextField txtCarros;
    // End of variables declaration//GEN-END:variables
}
